# Make sure that
#   * the additional_dependencies here match requirements.txt

ci:
  autoupdate_schedule: monthly

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.1
    hooks:
      - id: pylint
        args:
          - --rcfile=setup.cfg
          #  run pylint across multiple cpu cores to speed it up-
          - --jobs=0 # See https://pylint.pycqa.org/en/latest/user_guide/run.html?#parallel-execution to know more
        additional_dependencies:
          - fastapi~=0.75.0
          - uvicorn[standard]~=0.17.6
          - APScheduler~=3.9.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies:
          - fastapi~=0.75.0
          - uvicorn[standard]~=0.17.6
          - APScheduler~=3.9.1
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
